name: Test Jupyter notebook files

on:
  pull_request:
  push:
    branches:
    - main
    #   # - 'aus-**'
    #   # - 'dev-**'

jobs:
  build-docs:
    name: Jupyter-Notebook-QA
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get all the changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          since_last_remote_commit: true

      - name: Check for Jupyter notebook solutions in the PR.
        run: |
          if [[ ${{ steps.changed-files.outputs.all_changed_files }} =~ .*\.ipynb ]]; then
            echo "Jupyter notebooks found in the PR."
          else
            echo "No Jupyter notebooks found in the PR."
            exit 1
          fi

    # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: dev
          environment-file: env_files/environment.yml
          use-mamba: true

      - name: Build environment
        run:
          conda activate dev

      - name: Run script to test Jupyter notebooks
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # Check for Juptyer notebook solution files.
            if [[ $file == *solution.ipynb ]]; then
                echo "Testing $file"
                jupyter execute $file
            fi
          done
