name: Jupyter Notebooks

on:
  pull_request:
    branches:
    - main
    #   # - 'aus-**'
    #   # - 'dev-**'
    paths:
      # Only Jupyter notebooks files in the Lessons and Homework folders will trigger the action.
      - '**.ipynb'

jobs:
  build:
    name: Jupyter-Notebook-QA
    runs-on: ubuntu-latest
    # Required permissions to run the action
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          since_last_remote_commit: true
      - name: Get modified JN files
        working-directory: .jn-files
        run: |
          git config diff.renameLimit 99000
          git fetch origin $GITHUB_BASE_REF --depth=1
          touch files.txt
          if file in ${{ steps.changed-files.outputs.all_changed_files }} == *.ipynb; then
              echo "$file was changed"
              echo $file >> files.txt
            fi
          rm files.txt
          export filename_string=""
          for i in `ls`; do export filename_string=$filename_string", "$i; done
          echo "{filenames}={$filename_string}" >> $GITHUB_OUTPUT
