name: PyUnit Testing

on:
  pull_request:
  push:
    branches:
    - main
    #   # - 'aus-**'
    #   # - 'dev-**'
    paths-ignore:
      # Ignore these directories.
      - 'scripts/*.py'

jobs:
  build:
    name: Set up job
    runs-on: ubuntu-latest
    # Required permissions to run the action
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all the changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          since_last_remote_commit: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: PyUnit Testing
        run: |
          # Initialize an empty array to store the paths of solved files
          solved_files=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Check for Python solution files
            if [[ $file == *solved.py ]]; then
                # Add the path of the solved file to the array
                solved_files+=("$file")
                for solved_file in "${solved_files[@]}"; do
                    echo $(solved_file)
                    # Extract the directory name
                    solved_directory=$(dirname "$solved_file")
                    echo "In the $solved_directory directory"
                    # Construct absolute paths for Solved and Unsolved directories
                    # unsolved_dir="${solved_directory/\/Solved/\/Unsolved}"
                    # echo "Unsolved Directory: $unsolved_dir"
                    # Copy the solved.py file to the "Unsolved" subdirectory
                    mv solved.py ../Unsolved/solved.py
                    echo "Copied $file to unsolved directory"
                    # Rename the unsolved.py file to unsolved_tmp.py
                    mv ../Unsolved/unsolved.py ../Unsolved/unsolved_tmp.py
                    echo "Renamed unsolved.py to unsolved_tmp.py"
                    # Rename the solved.py file to unsolved.py
                    mv ../Unsolved/solved.py Unsolved/unsolved.py
                    # Run the test.py file on the unsolved.py file
                    echo "Testing unsolved file"
                    python ../Unsolved/tests.py
                    mv ../Unsolved/solved.py solved.py
                    echo "Moved unsolved.py back to solved.py"
                    # Move the unsolved_tmp.py file back to the "Unsolved" subdirectory
                    mv ../Unsolved/unsolved_tmp.py ../Unsovled/unsolved.py
                    echo "Moved unsolved_tmp.py back to unsolved.py"
                done
            fi
          done
