name: PyUnit Testing

on:
  pull_request:
  push:
    branches:
    - main
    #   # - 'aus-**'
    #   # - 'dev-**'
    paths-ignore:
      # Ignore these directories.
      - 'scripts/*.py'

jobs:
  build:
    name: Set up job
    runs-on: ubuntu-latest
    # Required permissions to run the action
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all the changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          since_last_remote_commit: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: PyUnit Testing
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Check for Python solution files
            if [[ $file == *solved.py ]]; then
                # Extract the directory name
                directory=$(dirname "$file")
                echo "Directory: $directory"
                # Change directory to the "Solved" subdirectory
                cd "$directory" || exit 1
                # Copy the solved.py file to the "Unsolved" subdirectory
                cp solved.py ../Unsolved
                # Change directory to the "Unsolved" subdirectory
                cd ../Unsolved || exit 1
                # Rename the unsolved.py file to unsolved_tmp.py
                mv unsolved.py unsolved_tmp.py
                # Rename the solved.py file to unsolved.py
                mv solved.py unsolved.py
                # Run the test.py file on the unsolved.py file
                echo "Testing unsolved file"
                python tests.py unsolved.py
                # Move the unsolved.py file back to the "Solved" subdirectory
                mv unsolved.py solved.py
                # Move the unsolved_tmp.py file back to the "Unsolved" subdirectory
                mv unsolved_tmp.py unsolved.py
                # Copy the solved.py file to the "Solved" subdirectory
                cp solved.py ../Solved
                # Return to the previous directory
                cd - || exit 1
            fi
          done
